### ISSUE TITLE
We Need Your HelloWorld

### ISSUE THREAD

**Issue by ghost1372** [ghost1372/HelloWorld-Hacktoberfest#2]
we need your hello world code in any language😊

> please create a folder called your github username and then create your helloworld in this folder

**Comment by vijay532** [comment]
as this is not a useful commit do they consider?

**Comment by ghost1372** [comment]
@vijay532  No, they don't care

**Comment by Amirhf1** [comment]
:+1:  accept

**Comment by mvklingeren** [comment]
Let me add one for Typescript with classes :-) 👍

**Comment by hidalgo-vntu** [comment]
add Python script

**Comment by chirag2120787** [comment]
Please review and accept https://github.com/ghost1372/HelloWorld-Hacktoberfest/pull/195

**Comment by ghost1372** [comment]
@chirag2120787  tnx for your pr, accepted😉
